from typing import Counter

texto = """
A fotografia todo mundo conhece. V-J Day in Times Square é aquela famosa imagem de um marinheiro norte-americano beijando uma jovem enfermeira naquela famosa avenida de Nova York. Essa mesma que ilustra o texto. A foto correu o mundo em 1945 através de uma edição da Revista Time transformando o beijo de dois desconhecidos em símbolo da alegria popular pelo fim da II Guerra Mundial. Da foto nasceu uma escultura de 7 metros de altura que se encontra hoje instalada em San Diego, Estados Unidos. É uma bela foto e também uma bela escultura, mas … Em 2014 um grupo feminista francês chamado Osez Le Feminisme, abriu uma petição pública exigindo que a escultura icônica fosse removida de uma exposição por se tratar, segundo o grupo, do registro de uma agressão sexual, de um crime, uma vez que o marinheiro não tinha o direito de beijar a enfermeira, mesmo ela tendo comentado que havia gostado do beijo. Ces la vie! Reportagem aqui.
Por essas e outras histórias (e estórias), o feminismo – nome popular para o Movimento de Emancipação das Mulheres, entrou na pauta das discussões dos principais meios de produção de conhecimento, assim como entrou também nas discussões mais corriqueiras da cultura através dos principais jornais, revistas e desenhos infantis de nossa época. Feminismo é conversa séria de programas transmitidos no começo de uma tarde dominical como aconteceu no programa da Regina Casé que teve como pautas assuntos como assédio moral, violência física, mercado profissional, autonomia econômica, estética feminina depois de uma chamada da apresentadora de que “as mulheres estão cansadas de serem tratadas como cidadãs de segundo classe”.
Mas entender o feminismo significa ter presente os diferentes momentos pelos quais passou a construção de suas diferentes identidades. Historiadores não estão bem certos se podemos falar de um movimento unívoco com uma epistemologia própria ou se o feminismo na verdade seria um fenômeno com o agrupamento de muitos movimentos de diferentes ideias e ações. Para maioria, a segunda posição é a mais adequada, pois, segundo eles, poderíamos no máximo captar características comuns dos diferentes feminismos. Isso porque, mesmo havendo uma gramática de reivindicações parcialmente comum conforme a época e as principais vozes, há divergências no modo como as reivindicações poderiam ser alcançadas a partir do ponto da justificativa do problema. Há feminismos de orientação individualista, liberal, radical ou marxista. E o modo como se organizam e as bandeiras que levantam como problemas fundacionais mudam sutilmente sua identidade cultural.
No Brasil os feminismos de vieses marxista e psicanalíticos parecem sobressair sobre os demais. Inclusive, parecem mesmo se inter-relacionarem. Os argumentos giram no sentido da importância do gênero e da luta de classes, analisando os modos como dois eixos paralelos, economia (capitalismo) e família (patriarcado) estruturam a vida das mulheres. Uma perspectiva ético-racial também tem ganhado força nos últimos dias. Por sua vez, as feministas de tendências psicanalíticas centram suas discussões na sexualidade como uma poderosa força cultural e ideológica ao postularem que as mulheres são oprimidas pelo fato desta força cultural ideológica da diferença sexual estar inscrita nos corpos e no inconsciente.
Mesmo não havendo espaço aqui para detalhar os vários períodos e identidades do feminismo, vale destacar a importância da sua primeira fase, nascida ali no século XVIII com a Declaração dos direitos da mulher e da cidadã, de Olympe de Gouges. Este é um período onde as mulheres não podiam assinar contratos, herdar propriedades, contratar advogados, votar e ter direitos sobre os filhos. Pelas leis da Inglaterra, por exemplo, o marido e a mulher eram uma só pessoa jurídica e a existência legal da mulher estava constituída na pessoa do marido, cuja a asa, proteção e tampa, ela executava a maioria das coisas do domínio público. A complexificação da sociedade demandava maior participação das mulheres na cena pública e um “novo homem” se constituía em sociedade através da ideia de cidadão. Era mais do que necessário que as mulheres se apresentassem marcando que este “novo homem” na verdade era homem e mulher. Neste estágio inicial, o movimento das mulheres se concentrou no sufrágio e se manteve inter-relacionado ao Movimento de Temperança (movimento de mulheres conservadoras pouco comentado pelos compêndios feministas) e ao Movimento Abolicionista. Este talvez seja o momento mais profícuo e importante das reivindicações femininas como movimento. Era onde nascia o modelo de sociedade e cidadania tal como a conhecemos e onde a bandeira da igualdade não se articulava sobre um discurso de oposição entre homens e mulheres, tal como vemos nos últimos dias.
Na teologia, segundo Ivone Gebara, freira católica, filósofa e teóloga feminista brasileira, a teologia feminista se tornou parte de uma revolução cultural que, segundo ela, ainda está em seus primeiros passos, tendo se desenvolvido a partir da segunda metade do século 20 inicialmente em alguns países da Europa Ocidental e nos Estados Unidos e a partir de 1980 na América Latina, África e Ásia, muito na esteira do espírito revolucionário presente na Teologia da Libertação. A trabalho das teólogas feministas, parte do ponto de que há uma dominação do ídolo divino masculino que marca e limita a vida das mulheres e o principal desafio dessa teologia é introduzir a metodologia da suspeita e da desconstrução de conceitos teológicos (Deus Pai, Deus Filho, Deus Espírito Santo, Pecado, Bem e Mal, Encarnação, Redenção e outros) verificando a origem e a pertinência em relação à experiência histórica e feminina. Esse trabalho é feito através da investigação dos textos da Bíblia considerados Palavra de Deus e da denúncia do mau uso do texto em vista da execução de políticas que favorecem a uns e desfavorecem a outros. Tudo na redução dualista de uma oposição em eventos que sempre podem apontar alguma trapaça. Não pode dar certo algo que começa pela pura suspeita e desconstrução, pode?! Aqui estamos na segunda para a terceira fase do momento feminista. Onde o discurso começa a pesar pela radicalidade de algumas posições.
Vejamos o que falou a feminista cristã Mary Daly, na faculdade de teologia da Universidade de Harvard: “indo direto ao assunto, proponho que castremos o Cristianismo e joguemos fora os frutos da sua arrogância masculina: os mitos do pecado e da salvação, que são simplesmente sintomas diferentes da mesma doença… Minha opinião é que a ideia de que a salvação veio ao mundo exclusivamente através de um salvador masculino perpetua o problema da opressão dos homens sobre as mulheres… o que está acontecendo hoje é que as mulheres estão se rebelando para castrar o sistema masculino que as castra e coloca Deus como “Pai” de todas as pessoas”. Outra disse ainda: “se a religião cristã não dá às mulheres recursos espirituais e intelectuais para que elas sintam satisfação em ter um emprego fora de casa, então talvez precisemos eliminar as imagens de família que enchem a Bíblia – começando com Deus como Pai e sua semelhança terrena, o pai de família”. Essas duas falas se encontram no livro De Volta ao Lar: do feminismo a realidade de Mary Pride e as suas escolhas se apresentam como uma tentativa de chamar atenção para o perigo da adoção de certas posições sem uma crítica adequada do assunto.
Susan T. Foh, em seu livro Women and the Word of God: A Response to Biblical Feminism, traduz essas falas de forma bastante perspicaz. Diz ela: “a questão mais importante que as feministas evangélicas debatem é de que modo a Bíblia deve ser interpretada… Elas acham que já a Bíblia foi escrita numa cultura onde a liderança pertencia totalmente ao pai de família, essa cultura influenciou os escritores da Bíblia a ter preconceitos contra os direitos das mulheres… De acordo com essa maneira de ver, há falhas e contradições na Bíblia. Aliás, essa opinião exalta a razão humana, pela qual o ser humano decide o que é e o que não é a palavra de Deus…. Para resumir, as feministas evangélicas veem contradições irreconciliáveis nos ensinos da Bíblia sobre as mulheres. Elas resolvem essas contradições reconhecendo que a Bíblia reflete as limitações humanas… as feministas evangélicas não acreditam que Deus nos deu sua palavra, que é verdadeira e digna de confiança, padrão imutável de fé e prática. Para elas, a Bíblia é uma mistura de informações (parte é a pura Palavra de Deus e parte sãos somente conselhos de homens moldados por sua cultura machista), e Deus nos deu a liberdade para imaginar quais as partes em que devemos acreditar e obedecer. A razão humana se torna a autoridade suprema, o juiz da Bíblia”. Onde ficou o critério de verdade em posições como essas?
Assim, podemos ensaiar uma primeira pergunta: é possível ser uma feminista cristã? Primeira coisa é entendermos que as crenças e convicções dentro do feminismo são muitos amplas, variadas e em alguns momentos contraditórias para que nos permita um julgamento final. Ideologias feministas se mostraram boas, neutras ou ruins, dependendo da especificidade da reivindicação quando colocada diante das crenças fundamentais da bíblia e de uma boa teologia moral e prática.
As boas e neutras e que aparecem nas reivindicações feministas mais antigas são aquelas que dizem respeito às mulheres serem respeitadas por si mesmas, sustentarem seus filhos, a terem direito sobre eles e serem respeitadas na situação de viuvez ou divórcio. Ensinamentos e ações de Jesus sinalizaram o respeito que as mulheres deveriam receber. Ele perdoou as mulheres de má reputação (João 8.1-11), falou respeitosamente a mulher samaritana (João 4.4-42) e interagiu com uma mulher impura (Mateus 9.20-22). Paulo também fez o reconhecimento de 10 mulheres em 26 pessoas que nomeou no capítulo 16 da carta aos Romanos, além de chamar primeiro Priscila, esposa de Áquila, para publicamente agradecer-lhes a própria vida. Tanto Paulo quanto Jesus realizando aqui ações em franco desacordo com o sistema religioso da época sem, no entanto, deixar de denunciar o pecado das condutas individuais das mulheres, assim também, como fazia com os homens. O que não ocorre em nossos dias, por exemplo. Falar de erro dentro de feminismo em vista de uma fala ou ação claramente demarcada é falta de sororidade ou método de desmerecimento do movimento. Pecado mortal e sem direito a perdão! Se houver ainda alguma dor ou trauma relacionado… esquece. Não há diálogo. Está tudo justificado, inclusive, com a imposição normativa do silêncio do outro. Faça da sua dor, a sua luta é o mote. Mas quem sabe chegará o dia que descobrirão que a dor não é um bom juiz e que sexo masculino e abusador não são necessariamente uma e mesma coisa?
Entre as ideologias ruins, pode-se destacar a crença de que as mulheres são mais importantes do que os homens (feminismo radical/ Matriarcado) e a de que mulheres e homens não teriam identidades (feminismo queer) orientadas já no evento da criação de Adam/Adão (homem e mulher), lá nos primórdios da humanidade. Essas são prerrogativas inquestionavelmente anticristãs mesmo que hajam grupos propondo leituras mais pluralistas desses e de outros princípios. Será mesmo que tudo é construção social e a identidade de gênero, a orientação sexual, o sexo biológico e o papel de gênero são coisas não-coincidentes e más às engrenagens sociais? Alas do atual feminismo, ou do pós feminismo para alguns, dizem que sim, como é o caso de Judith Butler, mas antropólogos como Mary C. Kuhn e Steven L. Stiner, da Universidade do Arizona, acreditam que foi exatamente a divisão de tarefas entre homens e mulheres que fizeram com que o homo sapiens vencesse os neandertais na luta pela sobrevivência. Há benefícios fáticos na família tal como a conhecemos e exceções devem ser tratadas como exceções e não como regras. Isso vale para ciências, mas também vale para os comportamentos. Também não podemos mais desconsiderar as descobertas vindas de áreas associadas às ciências biológicas sempre muito pouco comentadas nas discussões de moralidade e política. Não se enganem, há mais mistérios entre o céu e a terra do que supõem nossas vãs ciências sociais.
Com isso, assim como acontece a qualquer movimento, grupo político ou teoria, devemos julgar suas ações e mensagens por seus próprios méritos. Devemos julgar por aquilo que é dito em bloco e em seu próprio tempo, além claro, de julgar ações e mensagens individuais daqueles que postulam ser seus representantes. O que o feminismo diz defender em nossos dias? Quais os meios têm sido usados? Este é um dado importante. Avaliadas essas questões, se você acha que há ações e meios que possam ser legitimados em vista do tempo, das pessoas envolvidas e independentes da compreensão bíblica avaliada, testada, balizada e consensuada pela tradição, formada por homens e mulheres, sinto muito, mas talvez você esteja mais pautada por uma visão feminista de mundo do que uma visão cristã do mundo e do feminismo. Sabe aquela história de que ‘sou contra o aborto, mas acho que deveria ser legalizado de forma irrestrita por causa das mulheres pobres’? Enfim, vale pensar, repensar, avaliar, colocar diante da história chamada eternidade e pedir que Deus seja gracioso com todos nós. E se nosso comportamento nos revelar um referencial mais atrelado à queda do que à salvação em Cristo? Melhor será corrigir. Que sejamos luz e sal em um mundo gritando por soluções, mas perdido em suas discussões e problemas.
"""

def calcula_palavras(texto):
    print()
    dicionario_texto = Counter(texto.lower().split())
    conta_palavras = sum(dicionario_texto.values())
    print(f'Qtde palavras: {conta_palavras}')
    
    principais_palavras = [(palavra, frequencia) for palavra, frequencia in dicionario_texto.items() ]
    principais_palavras = Counter(dicionario_texto)
    top_palavras_comuns = principais_palavras.most_common(10)

    for palavra, frequencia in top_palavras_comuns:
        print(f'{palavra}: {frequencia / conta_palavras * 100 :.2f}%')

    print()

calcula_palavras(texto)
